[tool.black]
line-length = 99

[tool.codespell]
count = ""
ignore-regex = '\b[A-Z]{3}\b'
ignore-words-list = "ans,asend,deques,dout,extint,hsi,iput,numer,technic,ure"
quiet-level = 3
skip = """
*/build*,\
./.git,\
./drivers/cc3100,\
./lib,\
./ports/cc3200/FreeRTOS,\
./ports/cc3200/bootmgr/sl,\
./ports/cc3200/hal,\
./ports/cc3200/simplelink,\
./ports/cc3200/telnet,\
./ports/nrf/drivers/bluetooth/s1*,\
./ports/renesas-ra,\
./ports/stm32/usbhost,\
./tests,\
ACKNOWLEDGEMENTS,\
"""
